default_language_version:
  python: python3
default_stages: [pre-commit, manual]
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: ["--branch", main]
        stages: [pre-commit]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
      - id: check-yaml
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
  - repo: https://github.com/crate-ci/typos
    rev: codespell-dict-v0.5.0
    hooks:
      - id: typos
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort
        args:
          - --in-place
          - --trailing-comma-inline-array
          - --spaces-before-inline-comment=2
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--trailing-comma, all]
        exclude_types: [json]
