name: Dependabot PR

on:
  workflow_run:
    workflows: [Continuous Integration]
    types:
      - requested

permissions:
  pull-requests: write

jobs:
  auto-assign:
    name: Dependabot - Auto assign
    runs-on: ubuntu-latest
    if: ${{ ( github.actor == 'dependabot[bot]' || startsWith(github.event.workflow_run.head_branch, 'dependabot') ) && ( github.event.workflow_run.pull_requests[0].base.ref == github.event.repository.default_branch )}}
    steps:
      - name: Auto-assign issue
        env:
          assignee: ${{ secrets.DEFAULT_UPDATE_ASSIGNEE }}
        if: "${{ env.assignee != '' }}"
        uses: pozil/auto-assign-issue@v1.13.0
        with:
          assignees: ${{ env.assignee }}
