name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  pre_job:
    name: Skip checks
    runs-on: ubuntu-latest
    outputs:
      paths_result: ${{ steps.skip_check.outputs.paths_result }}
    steps:
      - name: Check skip workflows
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          paths_filter: |
            standard_checks:
              paths:
                - "**/**"

  standard_checks:
    name: Standard Checks
    needs: pre_job
    if: ${{ !fromJSON(needs.pre_job.outputs.paths_result).standard_checks.should_skip }}
    uses: ./.github/workflows/ci_standard_checks.yml
