on:
  workflow_call:

jobs:
  standard_checks:
    name: Standard Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.11"
          check-latest: true

      - name: Pip Cache
        uses: actions/cache@v3
        id: python_cache
        with:
          path: |
            env
            ~/.cache/pip
          key: env-${{ steps.setup_python.outputs.python-version }}-v2-${{ hashFiles('requirements/lint.txt') }}

      - name: Cache Pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-v2-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-v2-

      - name: Install linting dependencies
        if: ${{ steps.python_cache.outputs.cache-hit != 'true' }}
        run: |
          python -m pip install virtualenv --disable-pip-version-check
          python -m virtualenv env
          env/bin/python -m pip install -r requirements/lint.txt --disable-pip-version-check

      - name: Run Pre-commit - manual
        run: env/bin/python -m pre_commit run --all-files --hook-stage manual --verbose
